MODEL:
  TYPE: vit
  NAME: simmim_pretrain
  DROP_PATH_RATE: 0.0
  VIT:
    EMBED_DIM: 768
    DEPTH: 12
    NUM_HEADS: 12
    USE_APE: True
    USE_RPB: False
    USE_SHARED_RPB: True
    USE_MEAN_POOLING: False
    QKV_BIAS: True
    INIT_VALUES: None
DATA:
  IMG_SIZE: 224
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
TRAIN:
  EPOCHS: 200
  WARMUP_EPOCHS: 20
  BASE_LR: 2e-4
  WARMUP_LR: 1e-6
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER:
    NAME: 'multistep'
    GAMMA: 0.1
    MULTISTEPS: [700,]
PRINT_FREQ: 500
SAVE_FREQ: 20
TAG: simmim_pretrain__vit_base__img224__800ep
